extends:
  - airbnb
  - prettier
  - prettier/react
rules:
  import/prefer-default-export: 0
  react/jsx-filename-extension: 0
env:
  browser: true
  jest: true
  node: true
globals:
  page: true # used by puppeteer
